from tkinter import *
W = Tk()
W.title("POWERRRRRRRRRRRRRRRRRRRRR")
W.geometry("500x500")
def CONVERT(event):
        KW = float(EI.get())
        HP = KW * 1.341
        LR.config(text=f"{KW} KW = {HP} HP")
def CONVERT2(event):
        PS = float(EI2.get())
        HP = PS * 0.09863
        LR2.config(text=f"{PS} PS = {HP} HP")
def EXIT():
    W.destroy()
LI = Label(W, text="ENTER POWER IN KW:", font=("Arial", 12))
LI.pack(pady=10)
EI = Entry(W, font=("Arial", 12))
EI.pack(pady=10)
B = Button(W, text="CONVERT", bg="BLACK", fg="GREEN", font=("Arial", 12))
B.pack(pady=10)
B.bind("<Button-1>", CONVERT)
L =  Label(W, text="RESULT:-", font=("Arial", 12), fg="BLUE")
L.pack(pady=10)
LR = Label(W, text="", font=("Arial", 12), fg="BLUE")
LR.pack(pady=10)
LI2 = Label(W, text="ENTER POWER IN PS:", font=("Arial", 12))
LI2.pack(pady=10)
EI2 = Entry(W, font=("Arial", 12))
EI2.pack(pady=10)
B2 = Button(W, text="CONVERT", bg="BLACK", fg="GREEN", font=("Arial", 12))
B2.pack(pady=10)
B2.bind("<Button-1>", CONVERT2)
L2 =  Label(W, text="RESULT:-", font=("Arial", 12), fg="BLUE")
L2.pack(pady=10)
LR2 = Label(W, text="", font=("Arial", 12), fg="BLUE")
LR2.pack(pady=10)
exit_button = Button(W, text="Exit", bg="BLUE", fg="RED", font=("Arial", 12), command=EXIT)
exit_button.pack(pady=10)
W.mainloop()