import turtle
turtle.Screen().bgcolor("yellow")
turtle.Screen().setup(936,1000)
NG = turtle.Turtle()
for i in range(9):
    NG.forward(156)
    NG.left(40)
turtle.done()
NG = turtle.Turtle()
NG.left(10)  
NG.penup()
NG.forward(20)
NG.pendown()
for i in range(9):
    NG.forward(140)
    NG.left(40)
turtle.done()
NG = turtle.Turtle()
NG.left(20)
NG.penup()
NG.forward(40)
NG.pendown()
for i in range(9):
    NG.forward(130)
    NG.left(40)
turtle.done()
NG = turtle.Turtle()
NG.left(30)
NG.penup()
NG.forward(60)
NG.pendown()
for i in range(9):
    NG.forward(120)
    NG.left(40)
turtle.done()