LFA={'NAME':9857,'FORCED_INDUCTION':9857,'TIRE_SUPPLIER':9857,'ENGINE_TYPE':9857,'MAX  REACHABLE_REVVING_LIMIT':9857}
print("THE OG DICTIONARY WAS " + str(LFA))
MAX_REV=9857
IDK=0
for key in LFA:
    if LFA[key] == MAX_REV:
        IDK += 1
print("THE FREQUENCY OF THE MAX REV IS " + str(IDK))